version: "3"
services:
  app:
    build: ./docker_images/app
    volumes:
      - ./app/src:/usr/src/app
      - ./app/test:/usr/src/test
    # DBの立ち上がりに時間がかかるため、DBアクセスに失敗しないよう10秒待機してからflaskを実行する
    command: bash -c "sleep 10 && flask run --host=0.0.0.0 --debugger --reload"
    ports:
      - "5001:5000"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=pasuwaado
    volumes:
      - ./docker_images/db/init:/docker-entrypoint-initdb.d:cached
    ports:
      - "3388:3306"
  front:
    # DockerfileまでのPath
    build: ./docker_images/front
    # 環境変数を定義する
    environment:
      # Node.jsのグローバル変数: 開発用途なのでdevelopmentを指定
      - NODE_ENV=development
    # ホストマシン:コンテナ => ファイルを共有するための設定
    volumes:
      - ./front:/usr/src
    # Dockerコンテナ内で実行されるコマンドを指定する
    command: sh -c "cd src && npm install && yarn start"
    # ホストマシンPort番号:コンテナのPost番号
    ports:
      - 3000:3000
    # CLI画面の操作をできるようにする
    tty: true
