version: "3"
services:
  app:
    container_name: app
    build: ./docker_images/app
    volumes:
      - ./docker_images/app/src:/usr/src/app
    command: flask run --host=0.0.0.0 --debugger --reload
    ports:
      - "5001:5000"
  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=pasuwaado
    volumes:
      - ./docker_images/db/init:/docker-entrypoint-initdb.d:cached
    ports:
      - "3388:3306"
